### ISSUE TITLE
Azure Kubernetes Service (AKS) Reference Architecture

### ISSUE THREAD

**Issue by jcorioland** [Azure/terraform#5]
Complex Azure services such as AKS require many different decisions to be made on the creation of a cluster, and Terraform users have to create different templates for different combinations of deployment schemes(i.e. azureCNI with Virtual Node and Network Policy, kubenet with AAD RBAC,pod security and defined subnets, etc). This hack proposes to create a structured reference Terraform template that can use decision logic that can deploy different combinations of AKS setups depending on variables set.

**Comment by MarkWme** [comment]
I'd be interested in helping out on this one. Last year, I started work on some experimental Terraform scripts here - [https://github.com/MarkWme/TerraformExperiments](https://github.com/MarkWme/TerraformExperiments) - the AKS one does things like creating the Log Analytics workspace and using secrets from Key Vault. Keep meaning to revisit it and add more features, so may be able to use that as the starting point for a module.

**Comment by ams0** [comment]
keeping an eye on this one too.

**Comment by jcorioland** [comment]
@evillgenius75 published a first version of the module [here](https://registry.terraform.io/modules/evillgenius75/aks-nginx-certmgr/azurerm/0.1.1)
