### ISSUE TITLE
azapi_resource for Log Analytics Data Source not authenticating via azapi sp credentials in provider block

### ISSUE THREAD

**Issue by dsab123** [Azure/terraform#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

1.1.9

### Provider Version

0.1.1

### Current Behavior

When attempting to provision a Log Analytics Workspace via the `azapi_resource`, if I'm not authenticated via the az cli I get the following error:

```
│ Error: checking for presence of existing Resource: (ResourceId "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group/providers/Microsoft.OperationalInsights/workspaces/Log-Analytics-Workspace/dataSources/Logs-Ingest" / Api Version "2020-08-01"): DefaultAzureCredential: failed to acquire a token.
│ Attempted credentials:
│       EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
│       ManagedIdentityCredential: IMDS token request timed out
│       AzureCLICredential: ERROR: Please run 'az login' to setup account.
│ 
│ 
│   with azapi_resource.Logs-Ingest,
│   on ../../main.tf line 100, in resource "azapi_resource" "Logs-Ingest":
│ 100: resource "azapi_resource" "Logs-Ingest" {
```

If I `az login`, however, I can provision the resources just fine with a `terraform apply`.

### Expected Behavior

I expect to be able to manage a dataSource azapi_resource without having to `az login` if I'm authenticating via the service principal via the provider config block.

### Terraform configuration

```terraform
A valid `azapi` provider block:


provider "azapi" {
  client_id            = var.client_id
  environment          = var.environment
  subscription_id      = var.subscription_id
  tenant_id            = var.tenant_id
}
```

A valid `azapi_resource` data source declaration:
```
resource "azapi_resource" "Logs-Ingest" {
  provider  = azapi
  type      = "Microsoft.OperationalInsights/workspaces/dataSources@2020-08-01"
  name      = "Logs-Ingest"
  parent_id = azurerm_log_analytics_workspace.Log-Analytics-Workspace.id

  body = jsonencode({
    properties = {
      customLogName = "IngestLogs_CL"
      description = "Data Source to ingest /var/log/messages"
      inputs = [{
        location = {
          fileSystemLocations = {
            linuxFileTypeLogPaths = ["/var/log/messages"],
          }
        },
        recordDelimiter = {
          regexDelimiter = {
            pattern = "\\n",
            matchIndex = 0,
            numberdGroup = null
          }
        }
        }
      ],
      extractions = [
        {
          extractionName = "TimeGenerated",
          extractionType = "DateTime",
          extractionProperties = {
            dateTimeExtraction = {
              regex = null,
              joinStringRegex = null
            }
          }
        }
      ]
    }
    kind = "CustomLog"
  })
}

```

I will try to create an sscce tonight and post the repo here.

### Steps To Reproduce

`terraform plan` while not authenticated via cli should do it

### Anything else?

With `TF_LOG=json`, we get some more output. Various pastings of log messages below:

```
{"@level":"debug","@message":"Apr 26 20:59:27.925131 Retry: error Get \"http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01\u0026resource=https%3A%2F%2Fmanagement.core.windows.net%2F\": dial tcp 169.254.169.254:80: connect: host is down","@module":"provider.terraform-provider-azapi_v0.1.1","@timestamp":"2022-04-26T20:59:27.925495-04:00","timestamp":"2022-04-26T20:59:27.925-0400"}
```

I'm not sure why the Managed Data Service is being called to authenticate.

--------
EDIT: [Here's an sscce](https://github.com/dsab123/linux-vm-custom-logging-with-terraform-and-azapi)

**Comment by ms-henglu** [comment]
Hi @dsab123 ,

Thank you for taking time to report this issue!

It seems that `client_secret` is not declared in `azapi` provider block, please check https://registry.terraform.io/providers/Azure/azapi/latest/docs#client_secret.

More details can be found on https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/serivce_principal_client_sercret

**Comment by ms-henglu** [comment]
Hi @dsab123 ,

Thank you for taking time to report this issue!

It seems that `client_secret` is not declared in `azapi` provider block, please check https://registry.terraform.io/providers/Azure/azapi/latest/docs#client_secret.

More details can be found on https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/serivce_principal_client_sercret

**Comment by dsab123** [comment]
Oh my goodness, you're right. Totally missed it. Not a bug after all, at least not in `azapi` 😅 . 

Closing this! Thanks @ms-henglu, can't believe I missed that.
